import { NgModule } from '@angular/core';
import { MatButtonModule, MatIconModule, MatFormFieldModule, 
    MatInputModule, MatDatepickerModule, MatNativeDateModule, 
    MatCheckboxModule, 
    MatSidenavModule,
    MatToolbarModule,
    MatListModule,
    MatDialogModule,
    MatBadgeModule,
    MatRadioModule,
    MatSnackBarModule,
    MatTabsModule,
    MatCardModule,
    MatStepperModule,
    MatAutocompleteModule,
    MatSelectModule,
    MatTooltipModule,
    MatTableModule,
    MatSortModule,
    MatPaginatorModule} from '@angular/material';

@NgModule ({
    imports:[
        MatButtonModule,
        MatIconModule,
        MatFormFieldModule,
        MatInputModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatCheckboxModule,
        MatSidenavModule,
        MatToolbarModule,
        MatListModule,
        MatDialogModule,
        MatBadgeModule,
        MatRadioModule,
        MatSnackBarModule,
        MatTabsModule,
        MatCardModule,
        MatStepperModule,
        MatAutocompleteModule,
        MatSelectModule,
        MatTooltipModule,
        MatTableModule,
        MatSortModule,
        MatPaginatorModule
    ],
    exports:[
        MatButtonModule,
        MatIconModule,
        MatFormFieldModule,
        MatInputModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatCheckboxModule,
        MatSidenavModule,
        MatToolbarModule,
        MatListModule,
        MatDialogModule,
        MatBadgeModule,
        MatRadioModule,
        MatSnackBarModule,
        MatTabsModule,
        MatCardModule,
        MatStepperModule,
        MatAutocompleteModule,
        MatSelectModule,
        MatTooltipModule,
        MatTableModule,
        MatSortModule,
        MatPaginatorModule
    ]
})

export class MaterialModule {}